version: '3'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - .:/app
        depends_on:
            - mysql
        links:
            - mysql:${MYSQL_HOST_NAME:-mysql}

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "${NGINX_PORT_HTTP:-8000}:80"
            - "${NGINX_PORT_HTTPS:-4443}:443"
        volumes:
            - .:/app
            - ./docker/nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    mysql:
        image: mysql:5.7
        restart: unless-stopped
        ports:
            - "${MYSQL_PORT:-3309}:3306"
        volumes:
            - ./docker/mysql/:/docker-entrypoint-initdb.d/
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
            MYSQL_DATABASE: "${MYSQL_DATABASE:-minato_admin}"
            MYSQL_USER: "${MYSQL_USER:-app}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD:-secret}"

    frontend:
        image: node:14
        working_dir: /home/node
        restart: "no"
        volumes:
            - .:/home/node
        depends_on:
            - mysql
        command: npm run build

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: "pma"
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: "${MYSQL_USER:-app}"
            PMA_PASSWORD: "${MYSQL_PASSWORD:-secret}"


    mailhog:
        image: mailhog/mailhog
        container_name: "mailhog"
        ports:
            - "1025:1025"
            - "8025:8025"

